version: "3"

services:
  server:
    build: .
    container_name: edns-master
    network_mode: "host"
    environment:
      EAR7H_ENV: "prod"
    volumes:
      - "/var/ear7h/edns/:/var/ear7h/edns/"
    ports:
      - "443:443"
      - "4455:4455"